// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAuxBv7uHB1ma6ujEBQOxc2AJ_TW0BGI',
    appId: '1:716850994585:web:13fd82d4de7a57f4f34708',
    messagingSenderId: '716850994585',
    projectId: 'eiken-grade-1',
    authDomain: 'eiken-grade-1.firebaseapp.com',
    storageBucket: 'eiken-grade-1.appspot.com',
    measurementId: 'G-G5XJP0TF6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9E1lRqkZE04r9hoFp-74PwkdIZmwmxig',
    appId: '1:716850994585:android:9ba4c4643d89d611f34708',
    messagingSenderId: '716850994585',
    projectId: 'eiken-grade-1',
    storageBucket: 'eiken-grade-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_xcYRvCcP-5iJWvhHQbbbptoLuTGCos',
    appId: '1:716850994585:ios:7d106c8f14de1731f34708',
    messagingSenderId: '716850994585',
    projectId: 'eiken-grade-1',
    storageBucket: 'eiken-grade-1.appspot.com',
    iosClientId: '716850994585-vh0e8boh26if68qus8dmgv65eelcerdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eikenGrade1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_xcYRvCcP-5iJWvhHQbbbptoLuTGCos',
    appId: '1:716850994585:ios:7d106c8f14de1731f34708',
    messagingSenderId: '716850994585',
    projectId: 'eiken-grade-1',
    storageBucket: 'eiken-grade-1.appspot.com',
    iosClientId: '716850994585-vh0e8boh26if68qus8dmgv65eelcerdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eikenGrade1',
  );
}
